version: '3.7'
services:
   redis:
     image: redis:latest
     container_name: redis
     ports:
       - "16379:6379"
     volumes:
       - ./redis.conf:/etc/redis/redis.conf 
       - ./data:/data      
     command: redis-server /etc/redis/redis.conf 
     privileged: true